# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

 source 'https://github.com/ssamadgh/AOperationPod.git'

target 'CoreDataBooks_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreDataBooks_Swift
   pod 'AOperation'  

  target 'CoreDataBooks_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
